DROP TABLE roles_permisos;
DROP TABLE usuarios_eventos_crean;
DROP TABLE usuarios_eventos_reservan;
DROP TABLE eventos_metodos;
DROP TABLE eventos_categorias;
DROP TABLE usuarios;
DROP TABLE roles;
DROP TABLE IF EXISTS permisos;
DROP TABLE IF EXISTS eventos;
DROP TABLE IF EXISTS categorias;
DROP TABLE IF EXISTS metodos_pago;
